### ISSUE TITLE
Use monospace for code blocks

### ISSUE THREAD

**Issue by xaur** [decred/dcrdocs#1103]
![code-nonmono-1](https://user-images.githubusercontent.com/24484727/83897746-85f17f80-a745-11ea-9891-e70253af4cea.png)
![code-nonmono-2](https://user-images.githubusercontent.com/24484727/83897752-8853d980-a745-11ea-8a17-bb7ec8d465f5.png)

**Comment by xaur** [comment]
Firefox inspector tells me it is `fonts.css:60`, which has

```css
pre, code {
    /* use !important to prevent issues with browser extensions that change fonts */
    font-family: "dcrdocs-code", "Courier New", "monospace" !important;
}
```

Also, not sure if it's relevant or if the inspector is buggy, but in the Rules for the `<code>` element it shows

```
pre, code {
	font-family: "dcrdocs-code", "Courier New",! "monospace" importan";
}
```

Which looks like a malformed syntax.
